# Generated by Django 4.0.6 on 2022-08-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_usuarios_alter_meses_options_alter_meses_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meses',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
